version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  library_app:
    build: .
    container_name: library_app
    working_dir: /app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    command: python /app/main.py
    stdin_open: true
    tty: true
    volumes:
      - .:/app

volumes:
  mongo_data:
